# Generated by Django 3.2 on 2022-10-31 03:06

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[640, 480], upload_to=''),
            preserve_default=False,
        ),
    ]
